# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6fc19979d31e0b4476e2cfd23853b7f7"
name = "newsroom"
handle = "newsroom-5"
application_url = "https://remarkable-sq-else-replacing.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_draft_orders,read_files,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_themes,unauthenticated_read_content,unauthenticated_read_product_listings,write_content,write_files,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = ["https://remarkable-sq-else-replacing.trycloudflare.com/auth/callback", "https://remarkable-sq-else-replacing.trycloudflare.com/auth/shopify/callback", "https://remarkable-sq-else-replacing.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
