name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "yarn dlx prisma generate"
dev = "yarn dlx prisma migrate deploy && yarn remix vite:dev"