# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cee8ee508513d9fd031e6e8a453f8331"
name = "Newsroom"
handle = "newsroom"
application_url = "https://expert-seriously-testing-precipitation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "flarome-api.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_draft_orders,read_files,read_metaobjects,read_online_store_pages,read_orders,read_themes,unauthenticated_read_content,write_content,write_files,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://expert-seriously-testing-precipitation.trycloudflare.com/auth/callback",
  "https://expert-seriously-testing-precipitation.trycloudflare.com/auth/shopify/callback",
  "https://expert-seriously-testing-precipitation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://minister-configuring-reproduce-hepatitis.trycloudflare.com/webhooks/app/uninstalled"

[pos]
embedded = false
