# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5363397f9f0db456c06921f33dbab54d"
name = "Newsroom 2025"
handle = "newsroom-2025"
application_url = "https://complex-nl-developers-vii.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "flarome-api.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_draft_orders,read_files,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_themes,unauthenticated_read_content,write_content,write_files,write_metaobjects,write_products,write_themes"

[auth]
redirect_urls = [
  "https://complex-nl-developers-vii.trycloudflare.com/auth/callback",
  "https://complex-nl-developers-vii.trycloudflare.com/auth/shopify/callback",
  "https://complex-nl-developers-vii.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
