# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c27b14a7074536bc9aef8e70bf6bee24"
name = "Newsroom"
handle = "newsroom-3"
application_url = "https://insight-lp-yrs-boston.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_draft_orders,read_files,read_metaobject_definitions,read_metaobjects,read_online_store_pages,read_orders,read_themes,unauthenticated_read_content,unauthenticated_read_product_listings,write_content,write_files,write_metaobjects"

[auth]
redirect_urls = ["https://insight-lp-yrs-boston.trycloudflare.com/auth/callback", "https://insight-lp-yrs-boston.trycloudflare.com/auth/shopify/callback", "https://insight-lp-yrs-boston.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
