import { Extension } from "@tiptap/core"

interface UiState {
  /**
   * Indicates if AI generation is currently in selection mode
   * If its in selection mode, it means text generated by AI will be automatically accepted
   */
  lockDragHandle: boolean
}

declare module "@tiptap/core" {
  interface Commands<ReturnType> {
    uiState: {

      setLockDragHandle: (value: boolean) => ReturnType

      resetUiState: () => ReturnType
    }
  }

  interface Storage {
    uiState: UiState
  }
}

export const UiState = Extension.create<UiState>({
  name: "uiState",

  addStorage() {
    return {
      lockDragHandle: false,
    }
  },

  addCommands() {
    return {

      setLockDragHandle: (value: boolean) => () => {
        this.storage.lockDragHandle = value
        return true
      },


      resetUiState: () => () => {
        this.storage.lockDragHandle = false
        return true
      },
    }
  },

  onCreate() {
    this.storage = {
      lockDragHandle: false,
    }
  },
})
